project:
  type: website
  output-dir: docs

website:
  title: "Julio Sheinbaum"
  navbar:
   background: primary
   left:
     - href: index.qmd
       text: Home
     - about.qmd
     - presentation.qmd
     - cvprod.qmd # my new navbar page
     - basics_jupyter.qmd
     - bickley_julia.qmd
     - chap4.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



